### ISSUE TITLE
OS Viewer shows only one item of functional classification in tree map

### ISSUE THREAD

**Issue by fathoni** [openbudgets/integration#13]
OpenSpending OS viewer shows incomplete code list as one single box in tree map visualization. See [here](https://next.openspending.org/viewer/848b8e447d0dfc798a77ef4f3a7bbcbd:bonn-simplified-2017?measure=%22Plan2017.sum%22&groups%5B%5D=%22functional_classification_2.Produktbereich%22&order=%22Plan2017.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=en) for example.

**Comment by larjohn** [comment]
I am not sure if this is expected in Babbage:

https://openspending.org/api/3/cubes/848b8e447d0dfc798a77ef4f3a7bbcbd:bonn-simplified-2017/aggregate?drilldown=functional_classification_2.Produktbereich&order=Plan2017.sum:desc&pagesize=30

The `"functional_classification_2.Produktbereich": "6" `pair in the summary is suspectible, and also the  `"_count": 98`. 

Maybe @akariv can have a look on this?

**Comment by pwalsh** [comment]
Confirmed that I checked this now, and shared with the whole tech team. It looks like what we see here is exactly consistent with what was modelled in the [Fiscal Data Package](https://s3.amazonaws.com/datastore.openspending.org/848b8e447d0dfc798a77ef4f3a7bbcbd/bonn-simplified-2017/datapackage.json). 

Next action is for @fathoni to remodel.

**Comment by fathoni** [comment]
@pwalsh I have [this](https://github.com/openbudgets/integration/issues/16) problem upon attempting to redo the mapping on the OS packager.

**Comment by fathoni** [comment]
I may have misunderstood @pwalsh 's comment regarding the mapping. I think the mapping has already been correct since there are only functional classification and sub-functional classification available within the dataset. The problem is illustrated in the screenshot below:

![image](https://user-images.githubusercontent.com/1597027/29921045-824e4f90-8e50-11e7-8b20-7b4c6144e5df.png)

In the treemap, only functional classification with label '6' is visualized, but actually, there are more labels within this classification.

**Comment by pwalsh** [comment]
@vitorbaptista can you check if there is actually a bug here?

**Comment by vitorbaptista** [comment]
@fathoni Sorry for the late reply. The negative values in your dataset is what's causing these weird visualizations. A treemap isn't a good visualization for mixing positive/negative values, the only way I can see it working would be if we used different colours to differentiate between positive/negative values, and drew the rectangles using the absolute values. Even doing that, the comparison of the rectangles' sizes loose some of their meaning.

To make it easier to understand, we can think of a pie chart instead of a treemap, as even though they're visually different, they both show part to whole ratios. How would one have both positive and negative numbers in a pie chart?

If you're able to, I'd suggest using a bar chart instead.

**Comment by fathoni** [comment]
Thanks, Vitor, we also discussed with Paul yesterday regarding this. We agree that for the datasets that contain negative values (which apparently happens only in Bonn's case so far - or let me know if you found another case), tree map viz would be hidden. In the meantime in Bonn, we would also like to find a way to take care of this negative values. There is a lot more explanation actually for the datasets, but it is very specific to this case and separating the - (mostly revenue) / + (mostly expenditure) values on the datasets is currently not a feasible solution.
