### ISSUE TITLE
Deploying OBEU-stack locally

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/integration#2]
Hi @wk0206 , 
let me know if you can run OBEU locally in case you wish to do that. Updated Readme for the local installation.

For me it seems to work now.

**Comment by schmaluk** [comment]
For importing datasets into your local Virtuoso, you can download the datasets from here for example:
http://eis-openbudgets.iais.fraunhofer.de/dumps/Aragon/
http://eis-openbudgets.iais.fraunhofer.de/dumps/auxiliary-data/
http://eis-openbudgets.iais.fraunhofer.de/dumps/data-model/
http://eis-openbudgets.iais.fraunhofer.de/dumps/greek-municipalities/
and put them into your ./volumes/virtuosoStaging/upload folder.
For example via: wget -np -r -nH http://eis-openbudgets.iais.fraunhofer.de/dumps/auxiliary-data/
There is a cronjob for the import but it will run atm only once a day as specified in the cronjob here:
./docker-config/virtuoso/cronjobs/installCronjobs.sh
which can be reduced to run more frequently
Otherwise one can login into the virtuoso-Container and trigger the import manually by executing:
/cronjobs/importFromTrig
/cronjobs/importFromTTL

**Comment by wk0206** [comment]
thank you @mlukasch, most of the system run smoothly,

- Indigo is OK, but have to downgrade typescirpt to 2.1.4 to compile with issue
https://github.com/okgreece/indigo/issues/5#issuecomment-291829751

- a little spell mistake at README,
    - Mirosite: http://local,micro
should be http://local.micro

- linkpiple run on http://localhost:8181 instead of port 8080

- Rudolf report some error

I will continue with the work , if you can help will be great.
