### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by hantongliu** [openbudgets/integration#38]
Hi @larjohn , when I create an OBEU instance using another server, the tags in Indigo still link to apps.openbudgets.eu.

**Comment by larjohn** [comment]
This is because indigo was heavily themed to be the apps frontpage. So it has the project's footer right now. @seegerseeger might have a suggestion to resolve this.

**Comment by seegerseeger** [comment]
hi @larjohn, I sadly do not have an idea how to fix this, could it be part of the readme that the links need to be adapted when the server is cloned?

**Comment by skarampatakis** [comment]
@larjohn 

I think these are the links need to be changed since they are hardcoded. However some of them I'm not sure where they should pointing to, let say the "Blog" link.

https://github.com/okgreece/indigo/blob/cutting-edge/src/app/components/layout.ts

https://github.com/okgreece/indigo/blob/master/src/app/containers/cube/upload.ts

**Comment by larjohn** [comment]
This:
![image](https://user-images.githubusercontent.com/1288985/32300901-4cf6b0e0-bf64-11e7-85b6-4b3a39f1589f.png)

**Comment by hantongliu** [comment]
@larjohn @seegerseeger @skarampatakis , thanks for the help! Now problem is solved. I'll close this issue.
